eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true

server:
  port: 10055

spring:
  application:
    name: invitationService
  mail:
    host: smtp.gmail.com
    port: 587
    username: mail-address
    password: your password or google account -> activate two-step verification -> application password -> enter an application name and get a periodic password.
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    com:
      your package: DEBUG
  file:
    name: application.log


